# Generated by Django 2.0.7 on 2020-06-19 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usermembership',
            old_name='stripe_costomer_id',
            new_name='stripe_customer_id',
        ),
    ]
